<!DOCTYPE HTML>
<html>
<head>
<title>Holy Bible Ruby Rest</title>
<meta charset="utf-8" />
</head>
<body>
<h1>Holy Bible Ruby Rest</h1>

<img src="http://cfdb.owmconsulting.netdna-cdn.com/wp-content/uploads/2013/01/Holy-Bible.jpg" alt="Holy Bible">

<p>This application returns Bible verses in json format.</p>

<p>The translation of the Holy Bible used in this application is the <strong>King James</strong> version.</p>

<p>The application is very simple and easy to perform.</p>

<p>This application was developed with the Ruby programming language with the micro framework Sinatra and SQLite database.</p>

<h2>Instructions</h2>

<p>To start go to the directory where the application is through the console and run the <em>'bundle install'</em> command to install the application dependencies.</p>

<p>Then use the 'ruby app.rb' command to run the application.</p>

<p>View the application in the browser at the address: <em>'http://localhost:4567'</em>.</p>

<p>For some biblical verse format json enter the book abbreviation, chapter and verse number in the url number to get the desired passage.</p>

<h3>See the example:</h3>
<code>http://localhost:4567/book/Re/chapter/4/verse/10</code>

<h4>json Return</h4>
<pre>{"book":"Revelation","chapter":"4","verse":"10","text":"The four and twenty elders fall down before him that sat on the throne, and worship him that liveth for ever and ever, and cast their crowns before the throne, saying,"}</pre>

<h2>List of books with their respective abbreviations for you informed in the book the url parameter</h2>

<h3>Old Testament</h3>
<ol>
    <li>Genesis - Ge</li>
    <li>Exodus - Ex</li>
    <li>Leviticus - Le</li>
    <li>Numbers - Nu</li>
    <li>Deuteronomy - De</li>
    <li>Joshua - Jos</li>
    <li>Judges - Jg</li>
    <li>Ruth - Ru</li>
    <li>1 Samuel - 1Sa</li>
    <li>2 Samuel - 2Sa</li>
    <li>1 Kings - 1Ki</li>
    <li>2 Kings - 2Ki</li>
    <li>1 Chronicles - 1Ch</li>
    <li>2 Chronicles - 2Ch</li>
    <li>Ezra - Ezr</li>
    <li>Nehemiah - Ne</li>
    <li>Esther - Es</li>
    <li>Job - Job</li>
    <li>Psalms - Ps</li>
    <li>Proverbs - Pr</li>
    <li>Ecclesiastes - Ec</li>
    <li>Song of Solomon - Song</li>
    <li>Isaiah - Isa</li>
    <li>Jeremiah - Jer</li>
    <li>Lamentations - La</li>
    <li>Ezekiel - Eze</li>
    <li>Daniel - Da</li>
    <li>Hosea - Ho</li>
    <li>Joel - Joe</li>
    <li>Amos - Am</li>
    <li>Obadiah - Ob</li>
    <li>Jonah - Jon</li>
    <li>Micah - Mic</li>
    <li>Nahum - Na</li>
    <li>Habakkuk - Hab</li>
    <li>Zephaniah - Zep</li>
    <li>Haggai - Hag</li>
    <li>Zechariah - Zec</li>
    <li>Malachi - Mal</li>
</ol>

<h3>New Testament</h3>
<ol>
    <li>Matthew - Mt</li>
    <li>Mark - Mr</li>
    <li>Luke - Lu</li>
    <li>John - Joh</li>
    <li>Acts - Ac</li>
    <li>Romans - Ro</li>
    <li>1 Corinthians - 1Co</li>
    <li>2 Corinthians - 2Co</li>
    <li>Galatians - Ga</li>
    <li>Ephesians - Eph</li>
    <li>Philippians - Php</li>
    <li>Colossians - Col</li>
    <li>1 Thessalonians - 1Th</li>
    <li>2 Thessalonians - 2Th</li>
    <li>1 Timothy - 1Ti</li>
    <li>2 Timothy - 2Ti</li>
    <li>Titus - Tit</li>
    <li>Philemon - Phm</li>
    <li>Hebrews - Heb</li>
    <li>James - Jas</li>
    <li>1 Peter - 1Pe</li>
    <li>2 Peter - 2Pe</li>
    <li>1 John - 1Jo</li>
    <li>2 John - 2Jo</li>
    <li>3 John - 3Jo</li>
    <li>Jude - Jude</li>
    <li>Revelation - Re</li>
</ol>

</body>
</html>